AWSTemplateFormatVersion: "2010-09-09"
Description: "VueLambda - Support"

Parameters:
  S3BucketNameArtifacts:
    AllowedPattern: "(?=^.{3,63}$)(?!^(\\d+\\.){3}\\d+$)^(([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])$"
    ConstraintDescription: "S3BucketNameArtifacts must be a valid S3 bucket name. Allowed pattern: (?=^.{3,63}$)(?!^(\\d+\\.){3}\\d+$)^(([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])$"
    Description: "The S3 artifacts bucket name, e.g. artifacts.vue-lambda.com"
    Type: "String"
  S3BucketNameStatic:
    AllowedPattern: "(?=^.{3,63}$)(?!^(\\d+\\.){3}\\d+$)^(([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])$"
    ConstraintDescription: "S3BucketNameStatic must be a valid S3 bucket name. Allowed pattern: (?=^.{3,63}$)(?!^(\\d+\\.){3}\\d+$)^(([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])$"
    Description: "The S3 static bucket name, e.g. static.vue-lambda.com"
    Type: "String"

Resources:
  # CloudFront CloudFrontOriginAccessIdentity
  CloudFrontCloudFrontOriginAccessIdentity:
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "VueLambda - ${S3BucketNameStatic}"
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
  # S3
  S3BucketArtifacts:
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      BucketName: !Ref "S3BucketNameArtifacts"
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: "Enabled"
    Type: "AWS::S3::Bucket"
  S3BucketStatic:
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      BucketName: !Ref "S3BucketNameStatic"
    Type: "AWS::S3::Bucket"
  S3BucketPolicyStatic:
    DependsOn:
      - "CloudFrontCloudFrontOriginAccessIdentity"
      - "S3BucketStatic"
    Properties:
      Bucket: !Ref "S3BucketStatic"
      PolicyDocument:
        Id: !Sub "PolicyForCloudFrontPrivateContent-${CloudFrontCloudFrontOriginAccessIdentity}"
        Statement:
          - Action: "s3:GetObject"
            Effect: "Allow"
            Principal:
              AWS:
                - !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontCloudFrontOriginAccessIdentity}"
            Resource:
              - !Sub "${S3BucketStatic.Arn}/*"
            Sid: "Allow getting objects from S3"
    Type: "AWS::S3::BucketPolicy"

Outputs:
  # CloudFront CloudFrontOriginAccessIdentity
  CloudFrontCloudFrontOriginAccessIdentityId:
    Description: "VueLambda CloudFront Origin Access Identity Id"
    Export:
      Name: "VueLambdaCloudFrontCloudFrontOriginAccessIdentityId"
    Value: !Ref "CloudFrontCloudFrontOriginAccessIdentity"
  # S3 Buckets
  S3BucketArtifactsName:
    Description: "VueLambda S3 Bucket Artifacts Name"
    Export:
      Name: "VueLambdaS3BucketArtifactsName"
    Value: !Ref "S3BucketArtifacts"
  S3BucketStaticDomainName:
    Description: "VueLambda S3 Bucket Static Domain Name"
    Export:
      Name: "VueLambdaS3BucketStaticDomainName"
    Value: !GetAtt "S3BucketStatic.DomainName"
  S3BucketStaticName:
    Description: "VueLambda S3 Bucket Static Name"
    Export:
      Name: "VueLambdaS3BucketStaticName"
    Value: !Ref "S3BucketStatic"
